name: Release Creation

on: 
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Zip Files
      run: |
        zip -r module.zip module.json merchant-app.js merchant-app.html merchant-setup.html style.css

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v1
      with:
        files: module.zip
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
